[TP-51] 공통 input창 구현
retrospective6/TILBox pull request #21
Opened 2021-11-21 09:13 UTC by ksy90101

2021-11-21 10:06 UTC, hwookim reviewed
리뷰 남겼읍니다

2021-11-28 06:12 UTC, ksy90101 commented on client/src/components/Input.tsx
> +  height?: string;
선택변수로는 필요하지 않을까요?
모든 Input에서 heigth가 같을거 같지 않아서요.

2021-11-28 06:13 UTC, ksy90101 commented on client/src/components/Input.tsx
> +        {isValid ? <Text>{hint}</Text> : <Feedback>{feedback}</Feedback>}
근데 그렇게 하면 컴포넌트 계층이 이상해지는거 같아요.
Text를 Hint로 변경하는것 좋은거 같습니다.
Text라는 단어가 별로 좋은거 같지 않아서요.

2021-11-28 06:16 UTC, ksy90101 commented on client/src/components/Input.tsx
> +  placeholder: string;
rules에는 아무것도 안올 수 있을거 같아요.
아울러 말씀하신 부분들은 공감합니다 :) 수정해놓겠습니다!

2021-11-28 06:26 UTC, hwookim commented on client/src/components/Input.tsx
> +        {isValid ? <Text>{hint}</Text> : <Feedback>{feedback}</Feedback>}
저는 feedback도 hint의 일환이라고 생각했었어요.
큰 중복이 아니기도 하고, 선택에 맡기겠습니다! 👍🏼

2021-11-28 06:32 UTC, hwookim requested changes
중요한 로직이 하나 빠진 것 같아서 리뷰 남깁니다!

터지는 테스트와 코드 스멜도 한 번 확인 부탁드려요!

2021-11-28 06:32 UTC, hwookim commented on client/src/components/Input.tsx
> +  height: 30px;
이거 수정하다 바뀐 거 같은데,
현재 height가 적용되지 않고 있었네요!!
언제 바뀐거지... 😅 

height의 props 여부는 default 값이 figma에서 보여지는 것과 같기만 하다면 크게 상관 없는 문제기도 한 것 같아요.
두가지 중 한쪽으로 통일만 부탁드립니다! 👍🏼

2021-11-28 06:32 UTC, hwookim commented on client/src/components/Input.tsx
> +export default function Input(props: InputProps): JSX.Element {
그러고보니 `onChange`하거나 `onBlur`할 때 상위로 input의 값을 넘기는 로직이 없었네요!
props로 함수를 받아서 value를 넘기는 로직 추가 부탁드립니다 👀

2021-11-28 06:37 UTC, ksy90101 commented on client/src/components/Input.tsx
> +export default function Input(props: InputProps): JSX.Element {
무슨 말인지 이해가 안되요,,,
상위로 input값을 왜 넘겨야 하죠?

2021-11-28 06:38 UTC, hwookim commented on client/src/components/Input.tsx
> +export default function Input(props: InputProps): JSX.Element {
현재 상태에서 input을 쓰는 곳에서 input의 값에 어떻게 접근해서 value를 사용할 수 있나요?

2021-11-28 06:38 UTC, ksy90101 commented on client/src/components/Input.tsx
> +export default function Input(props: InputProps): JSX.Element {
디코 ㄱ

2021-11-28 06:53 UTC, hwookim commented on client/src/components/Input.tsx
> +export default function Input(props: InputProps): JSX.Element {
```tsx
// Parent.tsx
export default Parent() {
  const [inputValue, setInputValue] = useState("");
  
  const onBlurInput = (value) => {
    setInputValue(value);
    // some logic
  };
  
  return (
    <>
      <Input onBlur={onBlurInput} />
    </>
  )
}

// Input.tsx
export default Input({ onBlur }) {
  const onBlurInput = ({ target }) => {
    onBlur(target.value);
  };

  return <input onBlur={onBlurInput} />
}
```

이런식으로 보내야 상위에서 input value의 값을 가지고 api call을 하거나 할 수 있을 것 같아요!

2021-11-28 06:54 UTC, hwookim commented on client/src/components/Input.tsx
> +    `};
따로 default 값은 없나요?
figma에서 보는 친구들은 거의 같은 크기 같은 높이인데 매번 설정해주는 건 좀 비효율적일 것 같아요.

2021-11-28 06:56 UTC, ksy90101 commented on client/src/components/Input.tsx
> +export default function Input(props: InputProps): JSX.Element {
아 Input에 입력된 값을 상위 부모에서 받아야 한다고 말씀하시는거죠?

2021-11-28 06:59 UTC, hwookim commented on client/src/components/Input.tsx
> +export default function Input(props: InputProps): JSX.Element {
넵!!
그 값을 통해서 작업을 해야하니까요 👍🏼

2021-11-28 07:00 UTC, ksy90101 commented on client/src/components/Input.tsx
> +export default function Input(props: InputProps): JSX.Element {
오 넵!

2021-11-28 07:01 UTC, hwookim commented on client/src/components/Input.tsx
> +export default function Input(props: InputProps): JSX.Element {
앗 디코 ㄱ 못봤었네 ㅎㅎ;

2021-12-04 14:38 UTC, hwookim approved these changes

2021-12-04 14:48 UTC, merged