TP-62 회원가입 페이지 구현
retrospective6/TILBox pull request #30
Opened 2021-12-05 08:20 UTC by ksy90101

2021-12-05 08:32 UTC, hwookim commented on client/src/components/join/form/Form.styles.tsx
> +export const Form = styled.form``;
아무 스타일도 주지 않는데 굳이 나눌 필요는 없을 거 같아요.

2021-12-05 08:32 UTC, hwookim commented on client/src/pages/join/Index.tsx
> +export default function Index(): JSX.Element {
페이지 명을 명시해 주시고
파일 이름은 index.tsx로 바꿔주세요.

원래 signin-signup으로 제가 작업해두긴 했었는데,
이 부분은 통일해야겠네요.
개인적으로는 register나 signup이 더 나아보입니다.
join은 다른 용어로 더 사용될 여지가 많은 것 같아서요.

2021-12-05 08:32 UTC, hwookim commented on client/src/components/join/form/Form.tsx
> +export default function Form(): JSX.Element {
단순 폼이라고 하는 것 보단 좀 더 명확하게 하는 건 어떨까요?
import하다가 오용될 여지가 너무 많아질 것 같아요.

2021-12-05 08:32 UTC, hwookim commented on client/src/pages/join/Index.styles.tsx
> +export const Title = styled.h2``;
불필요한 행동인 것 같아요.

2021-12-06 08:08 UTC, hwookim requested changes
테스트에 대한 부담을 줄이자곤 했지만,
되도록이면 핵심 로직정도는 테스트가 있었으면 합니다.
현재 pr같은 경우에는 정상적으로 form 전송이 되는가 정도요.

2021-12-06 08:08 UTC, hwookim commented on client/src/components/signUp/form/Form.styles.tsx
> +    }
스타일링을 클래스로도 주고, 스타일 컴포넌트로도 주면 혼란이 커질 것 같아요.
코드 리팩토링이나 스타일 변경 과정에서 휴먼 에러가 나오기 쉬워지진 않을까요?

컴포넌트 내부에 접근해야한다던지, 그런 사항이 아니라면 되도록 별개의 스타일 컴포넌트로 구분하는 게 더 좋을 것 같습니다.

2021-12-06 08:08 UTC, hwookim commented on client/src/components/signUp/form/Form.tsx
> +        data-testid="email-input"
`data-testid`는 복붙의 페혜로 보이네요.
아래 인풋 모두요.

2021-12-06 08:08 UTC, hwookim commented on client/src/pages/signUp/index.tsx
> +        <p>프로필 사진은 수정 가능합니다.</p>
이건 취향 차이이기도 한데,
저같은 경우엔 p는 주로 문단, 긴 문장에 쓰고
이런 짧은 문구엔 span을 주로 씁니당

그냥 그렇다구요....ㅋㅋ 😅

2021-12-06 08:08 UTC, hwookim commented on client/src/pages/signUp/index.tsx
> +export const ProfileWrap = styled.div`
이 부분 뿐만 아니라,
Wrap보단 Wrapper가 의미적으로 더 맞지 않나 싶습니다!

2021-12-06 08:13 UTC, hwookim requested changes

2021-12-06 08:13 UTC, hwookim commented on client/src/pages/signUp/index.tsx
> +export default function Index(): JSX.Element {
SignUpPage라고 명시하는 편이 전 더 좋은 것 같아요.

2021-12-06 08:13 UTC, hwookim commented on client/src/components/signUp/form/Form.tsx
> +export default function Form(): JSX.Element {
그냥 Form이면 import할 때 혼란스럽지 않을까요.
적어도 SignUpForm 정도는 명시해주면 좋을 것 같습니다.

2021-12-06 08:13 UTC, hwookim commented on client/__stories__/pages/signUpIndex.stories.tsx
> +  title: 'signUpIndex',
```suggestion
  title: 'page/SignUpPage',
```
정도로 바꿔서 컴포넌트들과 구분짓는 건 어떨까요?

2021-12-06 08:14 UTC, hwookim approved these changes
리뷰 반영은 선택에 맡길게요.
제가 너무 불편하다 싶은건 따로 PR 생성하거나 하겠습니다!

2021-12-28 08:12 UTC, ksy90101 commented on client/src/components/signUp/form/Form.tsx
> +      />
type도 props로 받아야 겠네요,,

2021-12-28 08:15 UTC, ksy90101 commented on client/src/pages/signUp/index.tsx
> +        <p>프로필 사진은 수정 가능합니다.</p>
전 문장인 경우에는 p로 하는 편입니다.
한 문장으로 나타낼때는요. 한 문장에서 특정한 스타일을 줘야 할때는 span을 주는편이에요 :)

2021-12-28 08:17 UTC, ksy90101 commented on client/__stories__/pages/signUpIndex.stories.tsx
> +  title: 'signUpIndex',
오 이런 방법이 있군요.

2021-12-29 05:31 UTC, merged